### ISSUE TITLE
Issue parsing queries

### ISSUE THREAD

**Issue by 0xClpz** [goldibex/targaryen#147]
What I was trying to do:
[https://gist.github.com/0xClpz/045e180b7b24538967061240f28c2f17](https://gist.github.com/0xClpz/045e180b7b24538967061240f28c2f17)

What happens:
Error is thrown with:
`    
query: query is undefined

      at ParseError (node_modules/targaryen/lib/parser/statement/base.js:22:5)
      at IdentifierNode.inferType (node_modules/targaryen/lib/parser/statement/identifier.js:26:13)
      at IdentifierNode.Node (node_modules/targaryen/lib/parser/statement/base.js:50:30)
      at IdentifierNode (node_modules/targaryen/lib/parser/statement/identifier.js:18:1)
      at Function.from (node_modules/targaryen/lib/parser/statement/base.js:175:12)
      at MemberNode.init (node_modules/targaryen/lib/parser/statement/member.js:79:24)
      at MemberNode.Node (node_modules/targaryen/lib/parser/statement/base.js:49:10)
      at MemberNode (node_modules/targaryen/lib/parser/statement/member.js:15:1)
      at Function.from (node_modules/targaryen/lib/parser/statement/base.js:175:12)
      at BinaryNode.init (node_modules/targaryen/lib/parser/statement/binary.js:31:22)
      at BinaryNode.Node (node_modules/targaryen/lib/parser/statement/base.js:49:10)
      at BinaryNode (node_modules/targaryen/lib/parser/statement/binary.js:24:1)
      at Function.from (node_modules/targaryen/lib/parser/statement/base.js:175:12)
      at LogicalNode.init (node_modules/targaryen/lib/parser/statement/logical.js:19:22)
      at LogicalNode.Node (node_modules/targaryen/lib/parser/statement/base.js:49:10)
      at LogicalNode (node_modules/targaryen/lib/parser/statement/logical.js:16:1)
      at Function.from (node_modules/targaryen/lib/parser/statement/base.js:175:12)
      at ExpressionNode.init (node_modules/targaryen/lib/parser/statement/expression.js:16:28)
      at ExpressionNode.Node (node_modules/targaryen/lib/parser/statement/base.js:49:10)
      at ExpressionNode (node_modules/targaryen/lib/parser/statement/expression.js:13:1)
      at Function.from (node_modules/targaryen/lib/parser/statement/base.js:175:12)
      at new Rule (node_modules/targaryen/lib/parser/index.js:40:22)
      at Object.<anonymous>.exports.parse (node_modules/targaryen/lib/parser/index.js:108:10)
      at new RulesetNode (node_modules/targaryen/lib/database/ruleset.js:316:61)
      at RulesetNode.children.forEach.k (node_modules/targaryen/lib/database/ruleset.js:325:17)
      at Array.forEach (native)
      at new RulesetNode (node_modules/targaryen/lib/database/ruleset.js:324:14)
      at new Ruleset (node_modules/targaryen/lib/database/ruleset.js:103:17)
      at Object.<anonymous>.exports.create (node_modules/targaryen/lib/database/ruleset.js:411:10)
      at new Database (node_modules/targaryen/lib/database/index.js:41:26)
      at Object.<anonymous>.exports.create [as database] (node_modules/targaryen/lib/database/index.js:353:10)
      at Object.<anonymous> (src/tests/securityRules/payments.spec.js:21:38)
      at process._tickCallback (internal/process/next_tick.js:109:7)`

**Comment by dinoboff** [comment]
@0xClpz which targaryen version are you using?

**Comment by dinoboff** [comment]
I can reproduce the error with v3.0.5 but not with master.

**Comment by dinoboff** [comment]
@0xClpz supported in `latest` version.
